parser: babel-eslint
env:
  es6: true
  node: true
  browser: true
plugins:
  - react
  - prettier
settings:
  react:
    version: "16.6"
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - prettier/react
rules:
  react/prop-types: off
  prettier/prettier: error

overrides:
  - files: "**/*.test.js"
    env:
      jest: true
